/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file vehicle_status.msg */


#pragma once






struct vehicle_status_s {
	unsigned long long timestamp;
	unsigned long long nav_state_timestamp;
	unsigned long long failsafe_timestamp;
	unsigned long long armed_time;
	unsigned long long takeoff_time;
	unsigned int onboard_control_sensors_present;
	unsigned int onboard_control_sensors_enabled;
	unsigned int onboard_control_sensors_health;
	unsigned char nav_state;
	unsigned char arming_state;
	unsigned char hil_state;
	bool failsafe;
	unsigned char system_type;
	unsigned char system_id;
	unsigned char component_id;
	unsigned char vehicle_type;
	bool is_vtol;
	bool is_vtol_tailsitter;
	bool vtol_fw_permanent_stab;
	bool in_transition_mode;
	bool in_transition_to_fw;
	bool rc_signal_lost;
	unsigned char rc_input_mode;
	bool data_link_lost;
	unsigned char data_link_lost_counter;
	bool high_latency_data_link_lost;
	bool engine_failure;
	bool mission_failure;
	bool geofence_violated;
	unsigned char failure_detector_status;
	unsigned char latest_arming_reason;
	unsigned char latest_disarming_reason;
	unsigned char _padding0[4]; // required for logger

	static constexpr unsigned char ARMING_STATE_INIT = 0;
	static constexpr unsigned char ARMING_STATE_STANDBY = 1;
	static constexpr unsigned char ARMING_STATE_ARMED = 2;
	static constexpr unsigned char ARMING_STATE_STANDBY_ERROR = 3;
	static constexpr unsigned char ARMING_STATE_SHUTDOWN = 4;
	static constexpr unsigned char ARMING_STATE_IN_AIR_RESTORE = 5;
	static constexpr unsigned char ARMING_STATE_MAX = 6;
	static constexpr unsigned char FAILURE_NONE = 0;
	static constexpr unsigned char FAILURE_ROLL = 1;
	static constexpr unsigned char FAILURE_PITCH = 2;
	static constexpr unsigned char FAILURE_ALT = 4;
	static constexpr unsigned char FAILURE_EXT = 8;
	static constexpr unsigned char FAILURE_ARM_ESC = 16;
	static constexpr unsigned char HIL_STATE_OFF = 0;
	static constexpr unsigned char HIL_STATE_ON = 1;
	static constexpr unsigned char NAVIGATION_STATE_MANUAL = 0;
	static constexpr unsigned char NAVIGATION_STATE_ALTCTL = 1;
	static constexpr unsigned char NAVIGATION_STATE_POSCTL = 2;
	static constexpr unsigned char NAVIGATION_STATE_AUTO_MISSION = 3;
	static constexpr unsigned char NAVIGATION_STATE_AUTO_LOITER = 4;
	static constexpr unsigned char NAVIGATION_STATE_AUTO_RTL = 5;
	static constexpr unsigned char NAVIGATION_STATE_AUTO_LANDENGFAIL = 8;
	static constexpr unsigned char NAVIGATION_STATE_AUTO_LANDGPSFAIL = 9;
	static constexpr unsigned char NAVIGATION_STATE_ACRO = 10;
	static constexpr unsigned char NAVIGATION_STATE_UNUSED = 11;
	static constexpr unsigned char NAVIGATION_STATE_DESCEND = 12;
	static constexpr unsigned char NAVIGATION_STATE_TERMINATION = 13;
	static constexpr unsigned char NAVIGATION_STATE_OFFBOARD = 14;
	static constexpr unsigned char NAVIGATION_STATE_STAB = 15;
	static constexpr unsigned char NAVIGATION_STATE_UNUSED2 = 16;
	static constexpr unsigned char NAVIGATION_STATE_AUTO_TAKEOFF = 17;
	static constexpr unsigned char NAVIGATION_STATE_AUTO_LAND = 18;
	static constexpr unsigned char NAVIGATION_STATE_AUTO_FOLLOW_TARGET = 19;
	static constexpr unsigned char NAVIGATION_STATE_AUTO_PRECLAND = 20;
	static constexpr unsigned char NAVIGATION_STATE_ORBIT = 21;
	static constexpr unsigned char NAVIGATION_STATE_MAX = 22;
	static constexpr unsigned char RC_IN_MODE_DEFAULT = 0;
	static constexpr unsigned char RC_IN_MODE_OFF = 1;
	static constexpr unsigned char RC_IN_MODE_GENERATED = 2;
	static constexpr unsigned char VEHICLE_TYPE_UNKNOWN = 0;
	static constexpr unsigned char VEHICLE_TYPE_ROTARY_WING = 1;
	static constexpr unsigned char VEHICLE_TYPE_FIXED_WING = 2;
	static constexpr unsigned char VEHICLE_TYPE_ROVER = 3;
	static constexpr unsigned char VEHICLE_TYPE_AIRSHIP = 4;
	static constexpr unsigned char ARM_DISARM_REASON_TRANSITION_TO_STANDBY = 0;
	static constexpr unsigned char ARM_DISARM_REASON_RC_STICK = 1;
	static constexpr unsigned char ARM_DISARM_REASON_RC_SWITCH = 2;
	static constexpr unsigned char ARM_DISARM_REASON_COMMAND_INTERNAL = 3;
	static constexpr unsigned char ARM_DISARM_REASON_COMMAND_EXTERNAL = 4;
	static constexpr unsigned char ARM_DISARM_REASON_MISSION_START = 5;
	static constexpr unsigned char ARM_DISARM_REASON_SAFETY_BUTTON = 6;
	static constexpr unsigned char ARM_DISARM_REASON_AUTO_DISARM_LAND = 7;
	static constexpr unsigned char ARM_DISARM_REASON_AUTO_DISARM_PREFLIGHT = 8;
	static constexpr unsigned char ARM_DISARM_REASON_KILL_SWITCH = 9;
	static constexpr unsigned char ARM_DISARM_REASON_LOCKDOWN = 10;
	static constexpr unsigned char ARM_DISARM_REASON_FAILURE_DETECTOR = 11;
	static constexpr unsigned char ARM_DISARM_REASON_SHUTDOWN = 12;
	static constexpr unsigned char ARM_DISARM_REASON_UNIT_TEST = 13;
};
